package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;
import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table a_f_approval_log
 */
public class AfApprovalLog extends BaseModel {
    /**
     * Database Column Remarks:
     *   id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.approval_no
     *
     * @mbg.generated
     */
    private String approvalNo;

    /**
     * Database Column Remarks:
     *   审批流实例编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.instance_no
     *
     * @mbg.generated
     */
    private String instanceNo;

    /**
     * Database Column Remarks:
     *   角色Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.role_id
     *
     * @mbg.generated
     */
    private String roleId;

    /**
     * Database Column Remarks:
     *   用户Id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.user_id
     *
     * @mbg.generated
     */
    private String userId;

    /**
     * Database Column Remarks:
     *   是否已经审批，0：未审批；1：已审批
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.is_approval
     *
     * @mbg.generated
     */
    private Integer isApproval;

    /**
     * Database Column Remarks:
     *   审批时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.approval_time
     *
     * @mbg.generated
     */
    private Date approvalTime;

    /**
     * Database Column Remarks:
     *   审批备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.remark
     *
     * @mbg.generated
     */
    private String remark;

    /**
     * Database Column Remarks:
     *   审批顺序
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.sort
     *
     * @mbg.generated
     */
    private Integer sort;

    /**
     * Database Column Remarks:
     *   用户选择，0：拒绝；1：同意
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.option
     *
     * @mbg.generated
     */
    private Integer option;

    /**
     * Database Column Remarks:
     *   审批流配置编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.config_no
     *
     * @mbg.generated
     */
    private String configNo;

    /**
     * Database Column Remarks:
     *   项目编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.project_no
     *
     * @mbg.generated
     */
    private String projectNo;

    /**
     * Database Column Remarks:
     *   排期编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column a_f_approval_log.schedule_sort
     *
     * @mbg.generated
     */
    private Integer scheduleSort;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.id
     *
     * @return the value of a_f_approval_log.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.id
     *
     * @param id the value for a_f_approval_log.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.approval_no
     *
     * @return the value of a_f_approval_log.approval_no
     *
     * @mbg.generated
     */
    public String getApprovalNo() {
        return approvalNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.approval_no
     *
     * @param approvalNo the value for a_f_approval_log.approval_no
     *
     * @mbg.generated
     */
    public void setApprovalNo(String approvalNo) {
        this.approvalNo = approvalNo == null ? null : approvalNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.instance_no
     *
     * @return the value of a_f_approval_log.instance_no
     *
     * @mbg.generated
     */
    public String getInstanceNo() {
        return instanceNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.instance_no
     *
     * @param instanceNo the value for a_f_approval_log.instance_no
     *
     * @mbg.generated
     */
    public void setInstanceNo(String instanceNo) {
        this.instanceNo = instanceNo == null ? null : instanceNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.role_id
     *
     * @return the value of a_f_approval_log.role_id
     *
     * @mbg.generated
     */
    public String getRoleId() {
        return roleId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.role_id
     *
     * @param roleId the value for a_f_approval_log.role_id
     *
     * @mbg.generated
     */
    public void setRoleId(String roleId) {
        this.roleId = roleId == null ? null : roleId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.user_id
     *
     * @return the value of a_f_approval_log.user_id
     *
     * @mbg.generated
     */
    public String getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.user_id
     *
     * @param userId the value for a_f_approval_log.user_id
     *
     * @mbg.generated
     */
    public void setUserId(String userId) {
        this.userId = userId == null ? null : userId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.is_approval
     *
     * @return the value of a_f_approval_log.is_approval
     *
     * @mbg.generated
     */
    public Integer getIsApproval() {
        return isApproval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.is_approval
     *
     * @param isApproval the value for a_f_approval_log.is_approval
     *
     * @mbg.generated
     */
    public void setIsApproval(Integer isApproval) {
        this.isApproval = isApproval;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.approval_time
     *
     * @return the value of a_f_approval_log.approval_time
     *
     * @mbg.generated
     */
    public Date getApprovalTime() {
        return approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.approval_time
     *
     * @param approvalTime the value for a_f_approval_log.approval_time
     *
     * @mbg.generated
     */
    public void setApprovalTime(Date approvalTime) {
        this.approvalTime = approvalTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.remark
     *
     * @return the value of a_f_approval_log.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.remark
     *
     * @param remark the value for a_f_approval_log.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.sort
     *
     * @return the value of a_f_approval_log.sort
     *
     * @mbg.generated
     */
    public Integer getSort() {
        return sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.sort
     *
     * @param sort the value for a_f_approval_log.sort
     *
     * @mbg.generated
     */
    public void setSort(Integer sort) {
        this.sort = sort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.option
     *
     * @return the value of a_f_approval_log.option
     *
     * @mbg.generated
     */
    public Integer getOption() {
        return option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.option
     *
     * @param option the value for a_f_approval_log.option
     *
     * @mbg.generated
     */
    public void setOption(Integer option) {
        this.option = option;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.config_no
     *
     * @return the value of a_f_approval_log.config_no
     *
     * @mbg.generated
     */
    public String getConfigNo() {
        return configNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.config_no
     *
     * @param configNo the value for a_f_approval_log.config_no
     *
     * @mbg.generated
     */
    public void setConfigNo(String configNo) {
        this.configNo = configNo == null ? null : configNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.project_no
     *
     * @return the value of a_f_approval_log.project_no
     *
     * @mbg.generated
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.project_no
     *
     * @param projectNo the value for a_f_approval_log.project_no
     *
     * @mbg.generated
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column a_f_approval_log.schedule_sort
     *
     * @return the value of a_f_approval_log.schedule_sort
     *
     * @mbg.generated
     */
    public Integer getScheduleSort() {
        return scheduleSort;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column a_f_approval_log.schedule_sort
     *
     * @param scheduleSort the value for a_f_approval_log.schedule_sort
     *
     * @mbg.generated
     */
    public void setScheduleSort(Integer scheduleSort) {
        this.scheduleSort = scheduleSort;
    }
}