package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * Database Table Remarks:
 *   基础字典数据
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table basics_data
 */
public class BasicsData extends BaseModel {
    /**
     * Database Column Remarks:
     *   主键ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.id
     *
     * @mbg.generated
     */
    @ApiModelProperty("主键ID")
    private String id;

    /**
     * Database Column Remarks:
     *   基础数据编码code
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.basics_code
     *
     * @mbg.generated
     */
    @ApiModelProperty("基础数据编码code")
    private String basicsCode;

    /**
     * Database Column Remarks:
     *   基础编码名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.basics_name
     *
     * @mbg.generated
     */
    @ApiModelProperty("基础编码名称")
    private String basicsName;

    /**
     * Database Column Remarks:
     *   基础编码分组
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.basics_group
     *
     * @mbg.generated
     */
    @ApiModelProperty("基础编码分组")
    private String basicsGroup;

    /**
     * Database Column Remarks:
     *   备注
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.remark
     *
     * @mbg.generated
     */
    @ApiModelProperty("备注")
    private String remark;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.create_time
     *
     * @mbg.generated
     */
    @ApiModelProperty("创建时间")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   创建人名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.create_user_name
     *
     * @mbg.generated
     */
    @ApiModelProperty("创建人名称")
    private String createUserName;

    /**
     * Database Column Remarks:
     *   创建人ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.create_user_id
     *
     * @mbg.generated
     */
    @ApiModelProperty("创建人ID")
    private String createUserId;

    /**
     * Database Column Remarks:
     *   删除状态，1删除，2未删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column basics_data.del_state
     *
     * @mbg.generated
     */
    @ApiModelProperty("删除状态，1删除，2未删除")
    private Integer delState;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.id
     *
     * @return the value of basics_data.id
     *
     * @mbg.generated
     */
    public String getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.id
     *
     * @param id the value for basics_data.id
     *
     * @mbg.generated
     */
    public void setId(String id) {
        this.id = id == null ? null : id.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.basics_code
     *
     * @return the value of basics_data.basics_code
     *
     * @mbg.generated
     */
    public String getBasicsCode() {
        return basicsCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.basics_code
     *
     * @param basicsCode the value for basics_data.basics_code
     *
     * @mbg.generated
     */
    public void setBasicsCode(String basicsCode) {
        this.basicsCode = basicsCode == null ? null : basicsCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.basics_name
     *
     * @return the value of basics_data.basics_name
     *
     * @mbg.generated
     */
    public String getBasicsName() {
        return basicsName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.basics_name
     *
     * @param basicsName the value for basics_data.basics_name
     *
     * @mbg.generated
     */
    public void setBasicsName(String basicsName) {
        this.basicsName = basicsName == null ? null : basicsName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.basics_group
     *
     * @return the value of basics_data.basics_group
     *
     * @mbg.generated
     */
    public String getBasicsGroup() {
        return basicsGroup;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.basics_group
     *
     * @param basicsGroup the value for basics_data.basics_group
     *
     * @mbg.generated
     */
    public void setBasicsGroup(String basicsGroup) {
        this.basicsGroup = basicsGroup == null ? null : basicsGroup.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.remark
     *
     * @return the value of basics_data.remark
     *
     * @mbg.generated
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.remark
     *
     * @param remark the value for basics_data.remark
     *
     * @mbg.generated
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.create_time
     *
     * @return the value of basics_data.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.create_time
     *
     * @param createTime the value for basics_data.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.create_user_name
     *
     * @return the value of basics_data.create_user_name
     *
     * @mbg.generated
     */
    public String getCreateUserName() {
        return createUserName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.create_user_name
     *
     * @param createUserName the value for basics_data.create_user_name
     *
     * @mbg.generated
     */
    public void setCreateUserName(String createUserName) {
        this.createUserName = createUserName == null ? null : createUserName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.create_user_id
     *
     * @return the value of basics_data.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.create_user_id
     *
     * @param createUserId the value for basics_data.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column basics_data.del_state
     *
     * @return the value of basics_data.del_state
     *
     * @mbg.generated
     */
    public Integer getDelState() {
        return delState;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column basics_data.del_state
     *
     * @param delState the value for basics_data.del_state
     *
     * @mbg.generated
     */
    public void setDelState(Integer delState) {
        this.delState = delState;
    }
}