package cn.thinkfree.database.model;

import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.List;

public class FundsCompanyCashExample extends cn.thinkfree.core.model.AbstractDataAuth {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public FundsCompanyCashExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andIdIsNull() {
            addCriterion("id is null");
            return (Criteria) this;
        }

        public Criteria andIdIsNotNull() {
            addCriterion("id is not null");
            return (Criteria) this;
        }

        public Criteria andIdEqualTo(Long value) {
            addCriterion("id =", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotEqualTo(Long value) {
            addCriterion("id <>", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThan(Long value) {
            addCriterion("id >", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdGreaterThanOrEqualTo(Long value) {
            addCriterion("id >=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThan(Long value) {
            addCriterion("id <", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdLessThanOrEqualTo(Long value) {
            addCriterion("id <=", value, "id");
            return (Criteria) this;
        }

        public Criteria andIdIn(List<Long> values) {
            addCriterion("id in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotIn(List<Long> values) {
            addCriterion("id not in", values, "id");
            return (Criteria) this;
        }

        public Criteria andIdBetween(Long value1, Long value2) {
            addCriterion("id between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andIdNotBetween(Long value1, Long value2) {
            addCriterion("id not between", value1, value2, "id");
            return (Criteria) this;
        }

        public Criteria andCompanyNoIsNull() {
            addCriterion("company_no is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNoIsNotNull() {
            addCriterion("company_no is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNoEqualTo(String value) {
            addCriterion("company_no =", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoNotEqualTo(String value) {
            addCriterion("company_no <>", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoGreaterThan(String value) {
            addCriterion("company_no >", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoGreaterThanOrEqualTo(String value) {
            addCriterion("company_no >=", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoLessThan(String value) {
            addCriterion("company_no <", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoLessThanOrEqualTo(String value) {
            addCriterion("company_no <=", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoLike(String value) {
            addCriterion("company_no like", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoNotLike(String value) {
            addCriterion("company_no not like", value, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoIn(List<String> values) {
            addCriterion("company_no in", values, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoNotIn(List<String> values) {
            addCriterion("company_no not in", values, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoBetween(String value1, String value2) {
            addCriterion("company_no between", value1, value2, "companyNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNoNotBetween(String value1, String value2) {
            addCriterion("company_no not between", value1, value2, "companyNo");
            return (Criteria) this;
        }

        public Criteria andStateIsNull() {
            addCriterion("state is null");
            return (Criteria) this;
        }

        public Criteria andStateIsNotNull() {
            addCriterion("state is not null");
            return (Criteria) this;
        }

        public Criteria andStateEqualTo(Short value) {
            addCriterion("state =", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotEqualTo(Short value) {
            addCriterion("state <>", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThan(Short value) {
            addCriterion("state >", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateGreaterThanOrEqualTo(Short value) {
            addCriterion("state >=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThan(Short value) {
            addCriterion("state <", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateLessThanOrEqualTo(Short value) {
            addCriterion("state <=", value, "state");
            return (Criteria) this;
        }

        public Criteria andStateIn(List<Short> values) {
            addCriterion("state in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotIn(List<Short> values) {
            addCriterion("state not in", values, "state");
            return (Criteria) this;
        }

        public Criteria andStateBetween(Short value1, Short value2) {
            addCriterion("state between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andStateNotBetween(Short value1, Short value2) {
            addCriterion("state not between", value1, value2, "state");
            return (Criteria) this;
        }

        public Criteria andContractMoneyIsNull() {
            addCriterion("contract_money is null");
            return (Criteria) this;
        }

        public Criteria andContractMoneyIsNotNull() {
            addCriterion("contract_money is not null");
            return (Criteria) this;
        }

        public Criteria andContractMoneyEqualTo(BigDecimal value) {
            addCriterion("contract_money =", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyNotEqualTo(BigDecimal value) {
            addCriterion("contract_money <>", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyGreaterThan(BigDecimal value) {
            addCriterion("contract_money >", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("contract_money >=", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyLessThan(BigDecimal value) {
            addCriterion("contract_money <", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("contract_money <=", value, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyIn(List<BigDecimal> values) {
            addCriterion("contract_money in", values, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyNotIn(List<BigDecimal> values) {
            addCriterion("contract_money not in", values, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("contract_money between", value1, value2, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andContractMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("contract_money not between", value1, value2, "contractMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyIsNull() {
            addCriterion("arrearage_money is null");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyIsNotNull() {
            addCriterion("arrearage_money is not null");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyEqualTo(BigDecimal value) {
            addCriterion("arrearage_money =", value, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyNotEqualTo(BigDecimal value) {
            addCriterion("arrearage_money <>", value, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyGreaterThan(BigDecimal value) {
            addCriterion("arrearage_money >", value, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("arrearage_money >=", value, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyLessThan(BigDecimal value) {
            addCriterion("arrearage_money <", value, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("arrearage_money <=", value, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyIn(List<BigDecimal> values) {
            addCriterion("arrearage_money in", values, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyNotIn(List<BigDecimal> values) {
            addCriterion("arrearage_money not in", values, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("arrearage_money between", value1, value2, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andArrearageMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("arrearage_money not between", value1, value2, "arrearageMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyIsNull() {
            addCriterion("remaining_money is null");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyIsNotNull() {
            addCriterion("remaining_money is not null");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyEqualTo(BigDecimal value) {
            addCriterion("remaining_money =", value, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyNotEqualTo(BigDecimal value) {
            addCriterion("remaining_money <>", value, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyGreaterThan(BigDecimal value) {
            addCriterion("remaining_money >", value, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("remaining_money >=", value, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyLessThan(BigDecimal value) {
            addCriterion("remaining_money <", value, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("remaining_money <=", value, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyIn(List<BigDecimal> values) {
            addCriterion("remaining_money in", values, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyNotIn(List<BigDecimal> values) {
            addCriterion("remaining_money not in", values, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("remaining_money between", value1, value2, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andRemainingMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("remaining_money not between", value1, value2, "remainingMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyIsNull() {
            addCriterion("direct_money is null");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyIsNotNull() {
            addCriterion("direct_money is not null");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyEqualTo(BigDecimal value) {
            addCriterion("direct_money =", value, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyNotEqualTo(BigDecimal value) {
            addCriterion("direct_money <>", value, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyGreaterThan(BigDecimal value) {
            addCriterion("direct_money >", value, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("direct_money >=", value, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyLessThan(BigDecimal value) {
            addCriterion("direct_money <", value, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("direct_money <=", value, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyIn(List<BigDecimal> values) {
            addCriterion("direct_money in", values, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyNotIn(List<BigDecimal> values) {
            addCriterion("direct_money not in", values, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("direct_money between", value1, value2, "directMoney");
            return (Criteria) this;
        }

        public Criteria andDirectMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("direct_money not between", value1, value2, "directMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyIsNull() {
            addCriterion("goods_money is null");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyIsNotNull() {
            addCriterion("goods_money is not null");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyEqualTo(BigDecimal value) {
            addCriterion("goods_money =", value, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyNotEqualTo(BigDecimal value) {
            addCriterion("goods_money <>", value, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyGreaterThan(BigDecimal value) {
            addCriterion("goods_money >", value, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyGreaterThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_money >=", value, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyLessThan(BigDecimal value) {
            addCriterion("goods_money <", value, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyLessThanOrEqualTo(BigDecimal value) {
            addCriterion("goods_money <=", value, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyIn(List<BigDecimal> values) {
            addCriterion("goods_money in", values, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyNotIn(List<BigDecimal> values) {
            addCriterion("goods_money not in", values, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_money between", value1, value2, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andGoodsMoneyNotBetween(BigDecimal value1, BigDecimal value2) {
            addCriterion("goods_money not between", value1, value2, "goodsMoney");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNull() {
            addCriterion("shop_name is null");
            return (Criteria) this;
        }

        public Criteria andShopNameIsNotNull() {
            addCriterion("shop_name is not null");
            return (Criteria) this;
        }

        public Criteria andShopNameEqualTo(String value) {
            addCriterion("shop_name =", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotEqualTo(String value) {
            addCriterion("shop_name <>", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThan(String value) {
            addCriterion("shop_name >", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameGreaterThanOrEqualTo(String value) {
            addCriterion("shop_name >=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThan(String value) {
            addCriterion("shop_name <", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLessThanOrEqualTo(String value) {
            addCriterion("shop_name <=", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameLike(String value) {
            addCriterion("shop_name like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotLike(String value) {
            addCriterion("shop_name not like", value, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameIn(List<String> values) {
            addCriterion("shop_name in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotIn(List<String> values) {
            addCriterion("shop_name not in", values, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameBetween(String value1, String value2) {
            addCriterion("shop_name between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNameNotBetween(String value1, String value2) {
            addCriterion("shop_name not between", value1, value2, "shopName");
            return (Criteria) this;
        }

        public Criteria andShopNoIsNull() {
            addCriterion("shop_no is null");
            return (Criteria) this;
        }

        public Criteria andShopNoIsNotNull() {
            addCriterion("shop_no is not null");
            return (Criteria) this;
        }

        public Criteria andShopNoEqualTo(String value) {
            addCriterion("shop_no =", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoNotEqualTo(String value) {
            addCriterion("shop_no <>", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoGreaterThan(String value) {
            addCriterion("shop_no >", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoGreaterThanOrEqualTo(String value) {
            addCriterion("shop_no >=", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoLessThan(String value) {
            addCriterion("shop_no <", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoLessThanOrEqualTo(String value) {
            addCriterion("shop_no <=", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoLike(String value) {
            addCriterion("shop_no like", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoNotLike(String value) {
            addCriterion("shop_no not like", value, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoIn(List<String> values) {
            addCriterion("shop_no in", values, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoNotIn(List<String> values) {
            addCriterion("shop_no not in", values, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoBetween(String value1, String value2) {
            addCriterion("shop_no between", value1, value2, "shopNo");
            return (Criteria) this;
        }

        public Criteria andShopNoNotBetween(String value1, String value2) {
            addCriterion("shop_no not between", value1, value2, "shopNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameIsNull() {
            addCriterion("province_company_name is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameIsNotNull() {
            addCriterion("province_company_name is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameEqualTo(String value) {
            addCriterion("province_company_name =", value, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameNotEqualTo(String value) {
            addCriterion("province_company_name <>", value, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameGreaterThan(String value) {
            addCriterion("province_company_name >", value, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("province_company_name >=", value, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameLessThan(String value) {
            addCriterion("province_company_name <", value, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("province_company_name <=", value, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameLike(String value) {
            addCriterion("province_company_name like", value, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameNotLike(String value) {
            addCriterion("province_company_name not like", value, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameIn(List<String> values) {
            addCriterion("province_company_name in", values, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameNotIn(List<String> values) {
            addCriterion("province_company_name not in", values, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameBetween(String value1, String value2) {
            addCriterion("province_company_name between", value1, value2, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNameNotBetween(String value1, String value2) {
            addCriterion("province_company_name not between", value1, value2, "provinceCompanyName");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoIsNull() {
            addCriterion("province_company_no is null");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoIsNotNull() {
            addCriterion("province_company_no is not null");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoEqualTo(String value) {
            addCriterion("province_company_no =", value, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoNotEqualTo(String value) {
            addCriterion("province_company_no <>", value, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoGreaterThan(String value) {
            addCriterion("province_company_no >", value, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoGreaterThanOrEqualTo(String value) {
            addCriterion("province_company_no >=", value, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoLessThan(String value) {
            addCriterion("province_company_no <", value, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoLessThanOrEqualTo(String value) {
            addCriterion("province_company_no <=", value, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoLike(String value) {
            addCriterion("province_company_no like", value, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoNotLike(String value) {
            addCriterion("province_company_no not like", value, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoIn(List<String> values) {
            addCriterion("province_company_no in", values, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoNotIn(List<String> values) {
            addCriterion("province_company_no not in", values, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoBetween(String value1, String value2) {
            addCriterion("province_company_no between", value1, value2, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andProvinceCompanyNoNotBetween(String value1, String value2) {
            addCriterion("province_company_no not between", value1, value2, "provinceCompanyNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNameIsNull() {
            addCriterion("substation_name is null");
            return (Criteria) this;
        }

        public Criteria andSubstationNameIsNotNull() {
            addCriterion("substation_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubstationNameEqualTo(String value) {
            addCriterion("substation_name =", value, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameNotEqualTo(String value) {
            addCriterion("substation_name <>", value, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameGreaterThan(String value) {
            addCriterion("substation_name >", value, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameGreaterThanOrEqualTo(String value) {
            addCriterion("substation_name >=", value, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameLessThan(String value) {
            addCriterion("substation_name <", value, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameLessThanOrEqualTo(String value) {
            addCriterion("substation_name <=", value, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameLike(String value) {
            addCriterion("substation_name like", value, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameNotLike(String value) {
            addCriterion("substation_name not like", value, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameIn(List<String> values) {
            addCriterion("substation_name in", values, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameNotIn(List<String> values) {
            addCriterion("substation_name not in", values, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameBetween(String value1, String value2) {
            addCriterion("substation_name between", value1, value2, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNameNotBetween(String value1, String value2) {
            addCriterion("substation_name not between", value1, value2, "substationName");
            return (Criteria) this;
        }

        public Criteria andSubstationNoIsNull() {
            addCriterion("substation_no is null");
            return (Criteria) this;
        }

        public Criteria andSubstationNoIsNotNull() {
            addCriterion("substation_no is not null");
            return (Criteria) this;
        }

        public Criteria andSubstationNoEqualTo(String value) {
            addCriterion("substation_no =", value, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoNotEqualTo(String value) {
            addCriterion("substation_no <>", value, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoGreaterThan(String value) {
            addCriterion("substation_no >", value, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoGreaterThanOrEqualTo(String value) {
            addCriterion("substation_no >=", value, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoLessThan(String value) {
            addCriterion("substation_no <", value, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoLessThanOrEqualTo(String value) {
            addCriterion("substation_no <=", value, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoLike(String value) {
            addCriterion("substation_no like", value, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoNotLike(String value) {
            addCriterion("substation_no not like", value, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoIn(List<String> values) {
            addCriterion("substation_no in", values, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoNotIn(List<String> values) {
            addCriterion("substation_no not in", values, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoBetween(String value1, String value2) {
            addCriterion("substation_no between", value1, value2, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubstationNoNotBetween(String value1, String value2) {
            addCriterion("substation_no not between", value1, value2, "substationNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNull() {
            addCriterion("subject_name is null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIsNotNull() {
            addCriterion("subject_name is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectNameEqualTo(String value) {
            addCriterion("subject_name =", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotEqualTo(String value) {
            addCriterion("subject_name <>", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThan(String value) {
            addCriterion("subject_name >", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameGreaterThanOrEqualTo(String value) {
            addCriterion("subject_name >=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThan(String value) {
            addCriterion("subject_name <", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLessThanOrEqualTo(String value) {
            addCriterion("subject_name <=", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameLike(String value) {
            addCriterion("subject_name like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotLike(String value) {
            addCriterion("subject_name not like", value, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameIn(List<String> values) {
            addCriterion("subject_name in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotIn(List<String> values) {
            addCriterion("subject_name not in", values, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameBetween(String value1, String value2) {
            addCriterion("subject_name between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNameNotBetween(String value1, String value2) {
            addCriterion("subject_name not between", value1, value2, "subjectName");
            return (Criteria) this;
        }

        public Criteria andSubjectNoIsNull() {
            addCriterion("subject_no is null");
            return (Criteria) this;
        }

        public Criteria andSubjectNoIsNotNull() {
            addCriterion("subject_no is not null");
            return (Criteria) this;
        }

        public Criteria andSubjectNoEqualTo(String value) {
            addCriterion("subject_no =", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoNotEqualTo(String value) {
            addCriterion("subject_no <>", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoGreaterThan(String value) {
            addCriterion("subject_no >", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoGreaterThanOrEqualTo(String value) {
            addCriterion("subject_no >=", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoLessThan(String value) {
            addCriterion("subject_no <", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoLessThanOrEqualTo(String value) {
            addCriterion("subject_no <=", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoLike(String value) {
            addCriterion("subject_no like", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoNotLike(String value) {
            addCriterion("subject_no not like", value, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoIn(List<String> values) {
            addCriterion("subject_no in", values, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoNotIn(List<String> values) {
            addCriterion("subject_no not in", values, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoBetween(String value1, String value2) {
            addCriterion("subject_no between", value1, value2, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andSubjectNoNotBetween(String value1, String value2) {
            addCriterion("subject_no not between", value1, value2, "subjectNo");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNull() {
            addCriterion("company_name is null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIsNotNull() {
            addCriterion("company_name is not null");
            return (Criteria) this;
        }

        public Criteria andCompanyNameEqualTo(String value) {
            addCriterion("company_name =", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotEqualTo(String value) {
            addCriterion("company_name <>", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThan(String value) {
            addCriterion("company_name >", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameGreaterThanOrEqualTo(String value) {
            addCriterion("company_name >=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThan(String value) {
            addCriterion("company_name <", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLessThanOrEqualTo(String value) {
            addCriterion("company_name <=", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameLike(String value) {
            addCriterion("company_name like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotLike(String value) {
            addCriterion("company_name not like", value, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameIn(List<String> values) {
            addCriterion("company_name in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotIn(List<String> values) {
            addCriterion("company_name not in", values, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameBetween(String value1, String value2) {
            addCriterion("company_name between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andCompanyNameNotBetween(String value1, String value2) {
            addCriterion("company_name not between", value1, value2, "companyName");
            return (Criteria) this;
        }

        public Criteria andTypeIsNull() {
            addCriterion("type is null");
            return (Criteria) this;
        }

        public Criteria andTypeIsNotNull() {
            addCriterion("type is not null");
            return (Criteria) this;
        }

        public Criteria andTypeEqualTo(String value) {
            addCriterion("type =", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotEqualTo(String value) {
            addCriterion("type <>", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThan(String value) {
            addCriterion("type >", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeGreaterThanOrEqualTo(String value) {
            addCriterion("type >=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThan(String value) {
            addCriterion("type <", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLessThanOrEqualTo(String value) {
            addCriterion("type <=", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeLike(String value) {
            addCriterion("type like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotLike(String value) {
            addCriterion("type not like", value, "type");
            return (Criteria) this;
        }

        public Criteria andTypeIn(List<String> values) {
            addCriterion("type in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotIn(List<String> values) {
            addCriterion("type not in", values, "type");
            return (Criteria) this;
        }

        public Criteria andTypeBetween(String value1, String value2) {
            addCriterion("type between", value1, value2, "type");
            return (Criteria) this;
        }

        public Criteria andTypeNotBetween(String value1, String value2) {
            addCriterion("type not between", value1, value2, "type");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table funds_company_cash
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table funds_company_cash
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}