package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pc_system_log
 */
@ApiModel("日志")
public class LogInfo extends BaseModel implements Cloneable {
    /**
     * Database Column Remarks:
     *   主键
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.id

     */
    private Short id;

    /**
     * Database Column Remarks:
     *   所属模块
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.own_module

     */
    @ApiModelProperty("所属模块")
    private Short ownModule;

    /**
     * Database Column Remarks:
     *   操作类型
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.operation_type

     */
    @ApiModelProperty("操作类型")
    private Short operationType;

    /**
     * Database Column Remarks:
     *   客户IP
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.from_ip

     */
    private String fromIp;

    /**
     * Database Column Remarks:
     *   操作员
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.operator

     */
    private String operator;

    /**
     * Database Column Remarks:
     *   操作员名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.operator_name

     */
    private String operatorName;

    /**
     * Database Column Remarks:
     *   操作详情
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.details

     */
    private String details;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.create_time

     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   所属公司
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pc_system_log.company_id

     */
    private String companyId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.id
     *
     * @return the value of pc_system_log.id

     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.id
     *
     * @param id the value for pc_system_log.id

     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.own_module
     *
     * @return the value of pc_system_log.own_module

     */
    public Short getOwnModule() {
        return ownModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.own_module
     *
     * @param ownModule the value for pc_system_log.own_module

     */
    public void setOwnModule(Short ownModule) {
        this.ownModule = ownModule;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.operation_type
     *
     * @return the value of pc_system_log.operation_type

     */
    public Short getOperationType() {
        return operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.operation_type
     *
     * @param operationType the value for pc_system_log.operation_type

     */
    public void setOperationType(Short operationType) {
        this.operationType = operationType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.from_ip
     *
     * @return the value of pc_system_log.from_ip

     */
    public String getFromIp() {
        return fromIp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.from_ip
     *
     * @param fromIp the value for pc_system_log.from_ip

     */
    public void setFromIp(String fromIp) {
        this.fromIp = fromIp == null ? null : fromIp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.operator
     *
     * @return the value of pc_system_log.operator

     */
    public String getOperator() {
        return operator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.operator
     *
     * @param operator the value for pc_system_log.operator

     */
    public void setOperator(String operator) {
        this.operator = operator == null ? null : operator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.operator_name
     *
     * @return the value of pc_system_log.operator_name

     */
    public String getOperatorName() {
        return operatorName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.operator_name
     *
     * @param operatorName the value for pc_system_log.operator_name

     */
    public void setOperatorName(String operatorName) {
        this.operatorName = operatorName == null ? null : operatorName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.details
     *
     * @return the value of pc_system_log.details

     */
    public String getDetails() {
        return details;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.details
     *
     * @param details the value for pc_system_log.details

     */
    public void setDetails(String details) {
        this.details = details == null ? null : details.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.create_time
     *
     * @return the value of pc_system_log.create_time

     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.create_time
     *
     * @param createTime the value for pc_system_log.create_time

     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pc_system_log.company_id
     *
     * @return the value of pc_system_log.company_id

     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pc_system_log.company_id
     *
     * @param companyId the value for pc_system_log.company_id

     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }


    @Override
    public LogInfo clone() throws CloneNotSupportedException {
        return (LogInfo) super.clone();
    }
}