package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * Database Table Remarks:
 *   品牌主数据接口
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table materials_rem_brand
 */
@ApiModel(value="cn.thinkfree.database.model.MaterialsRemBrand")
public class MaterialsRemBrand extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="idnull")
    private Integer id;

    /**
     * Database Column Remarks:
     *   厂商工厂代码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.csbm
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="csbm厂商工厂代码")
    private String csbm;

    /**
     * Database Column Remarks:
     *   厂商工厂名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.csmc
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="csmc厂商工厂名称")
    private String csmc;

    /**
     * Database Column Remarks:
     *   品牌发展模式  直营/授权经销/加盟……
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.fzms
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="fzms品牌发展模式  直营/授权经销/加盟……")
    private String fzms;

    /**
     * Database Column Remarks:
     *   合作关系  管控类/非管控类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.hzgx
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="hzgx合作关系  管控类/非管控类")
    private String hzgx;

    /**
     * Database Column Remarks:
     *   品牌等级  VIP主力品牌/战盟主力品牌/一般品牌
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.jb
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="jb品牌等级  VIP主力品牌/战盟主力品牌/一般品牌")
    private String jb;

    /**
     * Database Column Remarks:
     *   连锁分类  进口/全国连锁/区域连锁
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.lsfl
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="lsfl连锁分类  进口/全国连锁/区域连锁")
    private String lsfl;

    /**
     * Database Column Remarks:
     *   联系人电话  联系人信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.lxrdh
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="lxrdh联系人电话  联系人信息")
    private String lxrdh;

    /**
     * Database Column Remarks:
     *   联系人名称  联系人信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.lxrmc
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="lxrmc联系人名称  联系人信息")
    private String lxrmc;

    /**
     * Database Column Remarks:
     *   联系人邮箱  联系人信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.lxryx
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="lxryx联系人邮箱  联系人信息")
    private String lxryx;

    /**
     * Database Column Remarks:
     *   联系人职务  联系人信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.lxrzw
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="lxrzw联系人职务  联系人信息")
    private String lxrzw;

    /**
     * Database Column Remarks:
     *   门店数量  连锁信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.mdsl
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="mdsl门店数量  连锁信息")
    private String mdsl;

    /**
     * Database Column Remarks:
     *   品牌档次  高端、低端、中端
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.ppdc
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="ppdc品牌档次  高端、低端、中端")
    private String ppdc;

    /**
     * Database Column Remarks:
     *   品牌风格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.ppfg
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="ppfg品牌风格")
    private String ppfg;

    /**
     * Database Column Remarks:
     *   品牌简介
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.ppjj
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="ppjj品牌简介")
    private String ppjj;

    /**
     * Database Column Remarks:
     *   品牌状态  库外/库内/合格/不合格/黑名单
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.ppzt
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="ppzt品牌状态  库外/库内/合格/不合格/黑名单")
    private String ppzt;

    /**
     * Database Column Remarks:
     *   品牌编号  品牌编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.sbbm
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="sbbm品牌编号  品牌编码")
    private String sbbm;

    /**
     * Database Column Remarks:
     *   品牌名称  品牌名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.sbmc
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="sbmc品牌名称  品牌名称")
    private String sbmc;

    /**
     * Database Column Remarks:
     *   品类大类  品类一级分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.spfl_1
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="spfl1品类大类  品类一级分类")
    private String spfl1;

    /**
     * Database Column Remarks:
     *   品类中类  品类二级分类
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.spfl_2
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="spfl2品类中类  品类二级分类")
    private String spfl2;

    /**
     * Database Column Remarks:
     *   REM数据记录版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.tm
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="tmREM数据记录版本号")
    private String tm;

    /**
     * Database Column Remarks:
     *   摊位数量  连锁信息
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.twsl
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="twsl摊位数量  连锁信息")
    private String twsl;

    /**
     * Database Column Remarks:
     *   版本号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.ver
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="ver版本号")
    private String ver;

    /**
     * Database Column Remarks:
     *   商标注册证号  商标注册证号作为唯一性识别号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.zczh
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="zczh商标注册证号  商标注册证号作为唯一性识别号")
    private String zczh;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.gmt_create
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="gmtCreatenull")
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   阿里编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_brand.albm
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="albm阿里编码")
    private String albm;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.id
     *
     * @return the value of materials_rem_brand.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.id
     *
     * @param id the value for materials_rem_brand.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.csbm
     *
     * @return the value of materials_rem_brand.csbm
     *
     * @mbg.generated
     */
    public String getCsbm() {
        return csbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.csbm
     *
     * @param csbm the value for materials_rem_brand.csbm
     *
     * @mbg.generated
     */
    public void setCsbm(String csbm) {
        this.csbm = csbm == null ? null : csbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.csmc
     *
     * @return the value of materials_rem_brand.csmc
     *
     * @mbg.generated
     */
    public String getCsmc() {
        return csmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.csmc
     *
     * @param csmc the value for materials_rem_brand.csmc
     *
     * @mbg.generated
     */
    public void setCsmc(String csmc) {
        this.csmc = csmc == null ? null : csmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.fzms
     *
     * @return the value of materials_rem_brand.fzms
     *
     * @mbg.generated
     */
    public String getFzms() {
        return fzms;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.fzms
     *
     * @param fzms the value for materials_rem_brand.fzms
     *
     * @mbg.generated
     */
    public void setFzms(String fzms) {
        this.fzms = fzms == null ? null : fzms.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.hzgx
     *
     * @return the value of materials_rem_brand.hzgx
     *
     * @mbg.generated
     */
    public String getHzgx() {
        return hzgx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.hzgx
     *
     * @param hzgx the value for materials_rem_brand.hzgx
     *
     * @mbg.generated
     */
    public void setHzgx(String hzgx) {
        this.hzgx = hzgx == null ? null : hzgx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.jb
     *
     * @return the value of materials_rem_brand.jb
     *
     * @mbg.generated
     */
    public String getJb() {
        return jb;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.jb
     *
     * @param jb the value for materials_rem_brand.jb
     *
     * @mbg.generated
     */
    public void setJb(String jb) {
        this.jb = jb == null ? null : jb.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.lsfl
     *
     * @return the value of materials_rem_brand.lsfl
     *
     * @mbg.generated
     */
    public String getLsfl() {
        return lsfl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.lsfl
     *
     * @param lsfl the value for materials_rem_brand.lsfl
     *
     * @mbg.generated
     */
    public void setLsfl(String lsfl) {
        this.lsfl = lsfl == null ? null : lsfl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.lxrdh
     *
     * @return the value of materials_rem_brand.lxrdh
     *
     * @mbg.generated
     */
    public String getLxrdh() {
        return lxrdh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.lxrdh
     *
     * @param lxrdh the value for materials_rem_brand.lxrdh
     *
     * @mbg.generated
     */
    public void setLxrdh(String lxrdh) {
        this.lxrdh = lxrdh == null ? null : lxrdh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.lxrmc
     *
     * @return the value of materials_rem_brand.lxrmc
     *
     * @mbg.generated
     */
    public String getLxrmc() {
        return lxrmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.lxrmc
     *
     * @param lxrmc the value for materials_rem_brand.lxrmc
     *
     * @mbg.generated
     */
    public void setLxrmc(String lxrmc) {
        this.lxrmc = lxrmc == null ? null : lxrmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.lxryx
     *
     * @return the value of materials_rem_brand.lxryx
     *
     * @mbg.generated
     */
    public String getLxryx() {
        return lxryx;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.lxryx
     *
     * @param lxryx the value for materials_rem_brand.lxryx
     *
     * @mbg.generated
     */
    public void setLxryx(String lxryx) {
        this.lxryx = lxryx == null ? null : lxryx.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.lxrzw
     *
     * @return the value of materials_rem_brand.lxrzw
     *
     * @mbg.generated
     */
    public String getLxrzw() {
        return lxrzw;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.lxrzw
     *
     * @param lxrzw the value for materials_rem_brand.lxrzw
     *
     * @mbg.generated
     */
    public void setLxrzw(String lxrzw) {
        this.lxrzw = lxrzw == null ? null : lxrzw.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.mdsl
     *
     * @return the value of materials_rem_brand.mdsl
     *
     * @mbg.generated
     */
    public String getMdsl() {
        return mdsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.mdsl
     *
     * @param mdsl the value for materials_rem_brand.mdsl
     *
     * @mbg.generated
     */
    public void setMdsl(String mdsl) {
        this.mdsl = mdsl == null ? null : mdsl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.ppdc
     *
     * @return the value of materials_rem_brand.ppdc
     *
     * @mbg.generated
     */
    public String getPpdc() {
        return ppdc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.ppdc
     *
     * @param ppdc the value for materials_rem_brand.ppdc
     *
     * @mbg.generated
     */
    public void setPpdc(String ppdc) {
        this.ppdc = ppdc == null ? null : ppdc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.ppfg
     *
     * @return the value of materials_rem_brand.ppfg
     *
     * @mbg.generated
     */
    public String getPpfg() {
        return ppfg;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.ppfg
     *
     * @param ppfg the value for materials_rem_brand.ppfg
     *
     * @mbg.generated
     */
    public void setPpfg(String ppfg) {
        this.ppfg = ppfg == null ? null : ppfg.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.ppjj
     *
     * @return the value of materials_rem_brand.ppjj
     *
     * @mbg.generated
     */
    public String getPpjj() {
        return ppjj;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.ppjj
     *
     * @param ppjj the value for materials_rem_brand.ppjj
     *
     * @mbg.generated
     */
    public void setPpjj(String ppjj) {
        this.ppjj = ppjj == null ? null : ppjj.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.ppzt
     *
     * @return the value of materials_rem_brand.ppzt
     *
     * @mbg.generated
     */
    public String getPpzt() {
        return ppzt;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.ppzt
     *
     * @param ppzt the value for materials_rem_brand.ppzt
     *
     * @mbg.generated
     */
    public void setPpzt(String ppzt) {
        this.ppzt = ppzt == null ? null : ppzt.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.sbbm
     *
     * @return the value of materials_rem_brand.sbbm
     *
     * @mbg.generated
     */
    public String getSbbm() {
        return sbbm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.sbbm
     *
     * @param sbbm the value for materials_rem_brand.sbbm
     *
     * @mbg.generated
     */
    public void setSbbm(String sbbm) {
        this.sbbm = sbbm == null ? null : sbbm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.sbmc
     *
     * @return the value of materials_rem_brand.sbmc
     *
     * @mbg.generated
     */
    public String getSbmc() {
        return sbmc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.sbmc
     *
     * @param sbmc the value for materials_rem_brand.sbmc
     *
     * @mbg.generated
     */
    public void setSbmc(String sbmc) {
        this.sbmc = sbmc == null ? null : sbmc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.spfl_1
     *
     * @return the value of materials_rem_brand.spfl_1
     *
     * @mbg.generated
     */
    public String getSpfl1() {
        return spfl1;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.spfl_1
     *
     * @param spfl1 the value for materials_rem_brand.spfl_1
     *
     * @mbg.generated
     */
    public void setSpfl1(String spfl1) {
        this.spfl1 = spfl1 == null ? null : spfl1.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.spfl_2
     *
     * @return the value of materials_rem_brand.spfl_2
     *
     * @mbg.generated
     */
    public String getSpfl2() {
        return spfl2;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.spfl_2
     *
     * @param spfl2 the value for materials_rem_brand.spfl_2
     *
     * @mbg.generated
     */
    public void setSpfl2(String spfl2) {
        this.spfl2 = spfl2 == null ? null : spfl2.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.tm
     *
     * @return the value of materials_rem_brand.tm
     *
     * @mbg.generated
     */
    public String getTm() {
        return tm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.tm
     *
     * @param tm the value for materials_rem_brand.tm
     *
     * @mbg.generated
     */
    public void setTm(String tm) {
        this.tm = tm == null ? null : tm.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.twsl
     *
     * @return the value of materials_rem_brand.twsl
     *
     * @mbg.generated
     */
    public String getTwsl() {
        return twsl;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.twsl
     *
     * @param twsl the value for materials_rem_brand.twsl
     *
     * @mbg.generated
     */
    public void setTwsl(String twsl) {
        this.twsl = twsl == null ? null : twsl.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.ver
     *
     * @return the value of materials_rem_brand.ver
     *
     * @mbg.generated
     */
    public String getVer() {
        return ver;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.ver
     *
     * @param ver the value for materials_rem_brand.ver
     *
     * @mbg.generated
     */
    public void setVer(String ver) {
        this.ver = ver == null ? null : ver.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.zczh
     *
     * @return the value of materials_rem_brand.zczh
     *
     * @mbg.generated
     */
    public String getZczh() {
        return zczh;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.zczh
     *
     * @param zczh the value for materials_rem_brand.zczh
     *
     * @mbg.generated
     */
    public void setZczh(String zczh) {
        this.zczh = zczh == null ? null : zczh.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.gmt_create
     *
     * @return the value of materials_rem_brand.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.gmt_create
     *
     * @param gmtCreate the value for materials_rem_brand.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_brand.albm
     *
     * @return the value of materials_rem_brand.albm
     *
     * @mbg.generated
     */
    public String getAlbm() {
        return albm;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_brand.albm
     *
     * @param albm the value for materials_rem_brand.albm
     *
     * @mbg.generated
     */
    public void setAlbm(String albm) {
        this.albm = albm == null ? null : albm.trim();
    }
}