package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.util.Date;

/**
 * Database Table Remarks:
 *   品类主数据接口
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table materials_rem_category
 */
@ApiModel(value="cn.thinkfree.database.model.MaterialsRemCategory")
public class MaterialsRemCategory extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.id
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="idnull")
    private Integer id;

    /**
     * Database Column Remarks:
     *   新增或修改  INSERT新增，UPDATE更新
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.datastatus
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="datastatus新增或修改  INSERT新增，UPDATE更新")
    private String datastatus;

    /**
     * Database Column Remarks:
     *   四级品类管控属性  分类层级=4，才可能有值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.depssplitorder
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="depssplitorder四级品类管控属性  分类层级=4，才可能有值")
    private String depssplitorder;

    /**
     * Database Column Remarks:
     *   四级品类拆单属性  分类层级=4，才可能有值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.deptcontrol
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="deptcontrol四级品类拆单属性  分类层级=4，才可能有值")
    private String deptcontrol;

    /**
     * Database Column Remarks:
     *   上级分类ID  分类层级=1时，此字段是空
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.fathercode
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="fathercode上级分类ID  分类层级=1时，此字段是空")
    private String fathercode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.gmt_create
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="gmtCreatenull")
    private Date gmtCreate;

    /**
     * Database Column Remarks:
     *   分类ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.levelcode
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="levelcode分类ID")
    private String levelcode;

    /**
     * Database Column Remarks:
     *   分类描述
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.leveldesc
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="leveldesc分类描述")
    private String leveldesc;

    /**
     * Database Column Remarks:
     *   分类层级  值是1到6，表示品类层级，市场只用到1级和2级
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.leveltype
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="leveltype分类层级  值是1到6，表示品类层级，市场只用到1级和2级")
    private String leveltype;

    /**
     * Database Column Remarks:
     *   四级维保期限  分类层级=4，才可能有值
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.maintainperiod
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="maintainperiod四级维保期限  分类层级=4，才可能有值")
    private String maintainperiod;

    /**
     * Database Column Remarks:
     *   组合品类ID  从第一层级开始分类ID组合
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column materials_rem_category.wholecode
     *
     * @mbg.generated
     */
    @ApiModelProperty(value="wholecode组合品类ID  从第一层级开始分类ID组合")
    private String wholecode;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.id
     *
     * @return the value of materials_rem_category.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.id
     *
     * @param id the value for materials_rem_category.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.datastatus
     *
     * @return the value of materials_rem_category.datastatus
     *
     * @mbg.generated
     */
    public String getDatastatus() {
        return datastatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.datastatus
     *
     * @param datastatus the value for materials_rem_category.datastatus
     *
     * @mbg.generated
     */
    public void setDatastatus(String datastatus) {
        this.datastatus = datastatus == null ? null : datastatus.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.depssplitorder
     *
     * @return the value of materials_rem_category.depssplitorder
     *
     * @mbg.generated
     */
    public String getDepssplitorder() {
        return depssplitorder;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.depssplitorder
     *
     * @param depssplitorder the value for materials_rem_category.depssplitorder
     *
     * @mbg.generated
     */
    public void setDepssplitorder(String depssplitorder) {
        this.depssplitorder = depssplitorder == null ? null : depssplitorder.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.deptcontrol
     *
     * @return the value of materials_rem_category.deptcontrol
     *
     * @mbg.generated
     */
    public String getDeptcontrol() {
        return deptcontrol;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.deptcontrol
     *
     * @param deptcontrol the value for materials_rem_category.deptcontrol
     *
     * @mbg.generated
     */
    public void setDeptcontrol(String deptcontrol) {
        this.deptcontrol = deptcontrol == null ? null : deptcontrol.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.fathercode
     *
     * @return the value of materials_rem_category.fathercode
     *
     * @mbg.generated
     */
    public String getFathercode() {
        return fathercode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.fathercode
     *
     * @param fathercode the value for materials_rem_category.fathercode
     *
     * @mbg.generated
     */
    public void setFathercode(String fathercode) {
        this.fathercode = fathercode == null ? null : fathercode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.gmt_create
     *
     * @return the value of materials_rem_category.gmt_create
     *
     * @mbg.generated
     */
    public Date getGmtCreate() {
        return gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.gmt_create
     *
     * @param gmtCreate the value for materials_rem_category.gmt_create
     *
     * @mbg.generated
     */
    public void setGmtCreate(Date gmtCreate) {
        this.gmtCreate = gmtCreate;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.levelcode
     *
     * @return the value of materials_rem_category.levelcode
     *
     * @mbg.generated
     */
    public String getLevelcode() {
        return levelcode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.levelcode
     *
     * @param levelcode the value for materials_rem_category.levelcode
     *
     * @mbg.generated
     */
    public void setLevelcode(String levelcode) {
        this.levelcode = levelcode == null ? null : levelcode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.leveldesc
     *
     * @return the value of materials_rem_category.leveldesc
     *
     * @mbg.generated
     */
    public String getLeveldesc() {
        return leveldesc;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.leveldesc
     *
     * @param leveldesc the value for materials_rem_category.leveldesc
     *
     * @mbg.generated
     */
    public void setLeveldesc(String leveldesc) {
        this.leveldesc = leveldesc == null ? null : leveldesc.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.leveltype
     *
     * @return the value of materials_rem_category.leveltype
     *
     * @mbg.generated
     */
    public String getLeveltype() {
        return leveltype;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.leveltype
     *
     * @param leveltype the value for materials_rem_category.leveltype
     *
     * @mbg.generated
     */
    public void setLeveltype(String leveltype) {
        this.leveltype = leveltype == null ? null : leveltype.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.maintainperiod
     *
     * @return the value of materials_rem_category.maintainperiod
     *
     * @mbg.generated
     */
    public String getMaintainperiod() {
        return maintainperiod;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.maintainperiod
     *
     * @param maintainperiod the value for materials_rem_category.maintainperiod
     *
     * @mbg.generated
     */
    public void setMaintainperiod(String maintainperiod) {
        this.maintainperiod = maintainperiod == null ? null : maintainperiod.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column materials_rem_category.wholecode
     *
     * @return the value of materials_rem_category.wholecode
     *
     * @mbg.generated
     */
    public String getWholecode() {
        return wholecode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column materials_rem_category.wholecode
     *
     * @param wholecode the value for materials_rem_category.wholecode
     *
     * @mbg.generated
     */
    public void setWholecode(String wholecode) {
        this.wholecode = wholecode == null ? null : wholecode.trim();
    }
}