package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * Database Table Remarks:
 *   施工队报表详情
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table pre_project_construction_info
 */
@ApiModel("报价单信息")
public class PreProjectConstructionInfo extends BaseModel {
    /**
     * Database Column Remarks:
     *   主键id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.id

     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   项目编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.project_no

     */
    private String projectNo;

    /**
     * Database Column Remarks:
     *   施工项目编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.construcion_project_no

     */
    @ApiModelProperty("施工项目编号")
    private String construcionProjectNo;

    /**
     * Database Column Remarks:
     *   说明
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.explain_info

     */
    @ApiModelProperty("说明")
    private String explainInfo;

    /**
     * Database Column Remarks:
     *   辅料名称规格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.material_name

     */
    @ApiModelProperty("辅料名称规格")
    private String materialName;

    /**
     * Database Column Remarks:
     *   验收标准
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.acceptance_criteria

     */
    @ApiModelProperty("验收标准")
    private String acceptanceCriteria;

    /**
     * Database Column Remarks:
     *   标准出处
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.standard_place

     */
    @ApiModelProperty("标注出处")
    private String standardPlace;

    /**
     * Database Column Remarks:
     *   项目创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.create_time

     */
    @ApiModelProperty("项目创建时间")
    private Date createTime;

    /**
     * Database Column Remarks:
     *   修改时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.update_time

     */
    private Date updateTime;

    /**
     * Database Column Remarks:
     *   状态
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.state

     */
    private Short state;

    /**
     * Database Column Remarks:
     *   是否删除 0未删除1已删除
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column pre_project_construction_info.is_delete

     */
    private Short isDelete;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.id
     *
     * @return the value of pre_project_construction_info.id

     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.id
     *
     * @param id the value for pre_project_construction_info.id

     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.project_no
     *
     * @return the value of pre_project_construction_info.project_no

     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.project_no
     *
     * @param projectNo the value for pre_project_construction_info.project_no

     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.construcion_project_no
     *
     * @return the value of pre_project_construction_info.construcion_project_no

     */
    public String getConstrucionProjectNo() {
        return construcionProjectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.construcion_project_no
     *
     * @param construcionProjectNo the value for pre_project_construction_info.construcion_project_no

     */
    public void setConstrucionProjectNo(String construcionProjectNo) {
        this.construcionProjectNo = construcionProjectNo == null ? null : construcionProjectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.explain_info
     *
     * @return the value of pre_project_construction_info.explain_info

     */
    public String getExplainInfo() {
        return explainInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.explain_info
     *
     * @param explainInfo the value for pre_project_construction_info.explain_info

     */
    public void setExplainInfo(String explainInfo) {
        this.explainInfo = explainInfo == null ? null : explainInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.material_name
     *
     * @return the value of pre_project_construction_info.material_name

     */
    public String getMaterialName() {
        return materialName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.material_name
     *
     * @param materialName the value for pre_project_construction_info.material_name

     */
    public void setMaterialName(String materialName) {
        this.materialName = materialName == null ? null : materialName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.acceptance_criteria
     *
     * @return the value of pre_project_construction_info.acceptance_criteria

     */
    public String getAcceptanceCriteria() {
        return acceptanceCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.acceptance_criteria
     *
     * @param acceptanceCriteria the value for pre_project_construction_info.acceptance_criteria

     */
    public void setAcceptanceCriteria(String acceptanceCriteria) {
        this.acceptanceCriteria = acceptanceCriteria == null ? null : acceptanceCriteria.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.standard_place
     *
     * @return the value of pre_project_construction_info.standard_place

     */
    public String getStandardPlace() {
        return standardPlace;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.standard_place
     *
     * @param standardPlace the value for pre_project_construction_info.standard_place

     */
    public void setStandardPlace(String standardPlace) {
        this.standardPlace = standardPlace == null ? null : standardPlace.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.create_time
     *
     * @return the value of pre_project_construction_info.create_time

     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.create_time
     *
     * @param createTime the value for pre_project_construction_info.create_time

     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.update_time
     *
     * @return the value of pre_project_construction_info.update_time

     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.update_time
     *
     * @param updateTime the value for pre_project_construction_info.update_time

     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.state
     *
     * @return the value of pre_project_construction_info.state

     */
    public Short getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.state
     *
     * @param state the value for pre_project_construction_info.state

     */
    public void setState(Short state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column pre_project_construction_info.is_delete
     *
     * @return the value of pre_project_construction_info.is_delete

     */
    public Short getIsDelete() {
        return isDelete;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column pre_project_construction_info.is_delete
     *
     * @param isDelete the value for pre_project_construction_info.is_delete

     */
    public void setIsDelete(Short isDelete) {
        this.isDelete = isDelete;
    }
}