package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;

/**
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table rebate_node
 */
public class RebateNode extends BaseModel {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate_node.id
     *
     * @mbg.generated
     */
    private Integer id;

    /**
     * Database Column Remarks:
     *   返款节点编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate_node.code
     *
     * @mbg.generated
     */
    private Integer code;

    /**
     * Database Column Remarks:
     *   返款节点名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate_node.name
     *
     * @mbg.generated
     */
    private String name;

    /**
     * Database Column Remarks:
     *   节点类型：1：设计订单；2：施工订单；3：经销商；
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column rebate_node.node_type
     *
     * @mbg.generated
     */
    private Integer nodeType;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate_node.id
     *
     * @return the value of rebate_node.id
     *
     * @mbg.generated
     */
    public Integer getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate_node.id
     *
     * @param id the value for rebate_node.id
     *
     * @mbg.generated
     */
    public void setId(Integer id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate_node.code
     *
     * @return the value of rebate_node.code
     *
     * @mbg.generated
     */
    public Integer getCode() {
        return code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate_node.code
     *
     * @param code the value for rebate_node.code
     *
     * @mbg.generated
     */
    public void setCode(Integer code) {
        this.code = code;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate_node.name
     *
     * @return the value of rebate_node.name
     *
     * @mbg.generated
     */
    public String getName() {
        return name;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate_node.name
     *
     * @param name the value for rebate_node.name
     *
     * @mbg.generated
     */
    public void setName(String name) {
        this.name = name == null ? null : name.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column rebate_node.node_type
     *
     * @return the value of rebate_node.node_type
     *
     * @mbg.generated
     */
    public Integer getNodeType() {
        return nodeType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column rebate_node.node_type
     *
     * @param nodeType the value for rebate_node.node_type
     *
     * @mbg.generated
     */
    public void setNodeType(Integer nodeType) {
        this.nodeType = nodeType;
    }
}