package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;
import java.util.Date;

/**
 * Database Table Remarks:
 *   预约项目
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table reserve_project
 */
public class ReserveProject extends BaseModel {
    /**
     * Database Column Remarks:
     *   业主姓名
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.owner_name
     *
     * @mbg.generated
     */
    private String ownerName;

    /**
     * Database Column Remarks:
     *   业主手机号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     * Database Column Remarks:
     *   装修地址
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.address
     *
     * @mbg.generated
     */
    private String address;

    /**
     * Database Column Remarks:
     *   来源（1,运营后台创建，2设计公司创建，3天猫，4业主预约）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.source
     *
     * @mbg.generated
     */
    private Integer source;

    /**
     * Database Column Remarks:
     *   装修风格
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.style
     *
     * @mbg.generated
     */
    private Integer style;

    /**
     * Database Column Remarks:
     *   装修预算
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.budget
     *
     * @mbg.generated
     */
    private String budget;

    /**
     * Database Column Remarks:
     *   房屋面积
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.acreage
     *
     * @mbg.generated
     */
    private String acreage;

    /**
     * Database Column Remarks:
     *   转换状态，1待转换，2已转换，3业主取消，4其他
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.state
     *
     * @mbg.generated
     */
    private Integer state;

    /**
     * Database Column Remarks:
     *   所属公司ID
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.company_id
     *
     * @mbg.generated
     */
    private String companyId;

    /**
     * Database Column Remarks:
     *   创建者userId
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.create_user_id
     *
     * @mbg.generated
     */
    private String createUserId;

    /**
     * Database Column Remarks:
     *   取消原因
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.reason
     *
     * @mbg.generated
     */
    private String reason;

    /**
     * Database Column Remarks:
     *   项目编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.project_no
     *
     * @mbg.generated
     */
    private String projectNo;

    /**
     * Database Column Remarks:
     *   设计订单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.design_order_no
     *
     * @mbg.generated
     */
    private String designOrderNo;

    /**
     * Database Column Remarks:
     *   预约单编号
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.reserve_no
     *
     * @mbg.generated
     */
    private String reserveNo;

    /**
     * Database Column Remarks:
     *   预约时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.reserve_time
     *
     * @mbg.generated
     */
    private Date reserveTime;

    /**
     * Database Column Remarks:
     *   订单转换时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column reserve_project.change_time
     *
     * @mbg.generated
     */
    private Date changeTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.owner_name
     *
     * @return the value of reserve_project.owner_name
     *
     * @mbg.generated
     */
    public String getOwnerName() {
        return ownerName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.owner_name
     *
     * @param ownerName the value for reserve_project.owner_name
     *
     * @mbg.generated
     */
    public void setOwnerName(String ownerName) {
        this.ownerName = ownerName == null ? null : ownerName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.phone
     *
     * @return the value of reserve_project.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.phone
     *
     * @param phone the value for reserve_project.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.address
     *
     * @return the value of reserve_project.address
     *
     * @mbg.generated
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.address
     *
     * @param address the value for reserve_project.address
     *
     * @mbg.generated
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.source
     *
     * @return the value of reserve_project.source
     *
     * @mbg.generated
     */
    public Integer getSource() {
        return source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.source
     *
     * @param source the value for reserve_project.source
     *
     * @mbg.generated
     */
    public void setSource(Integer source) {
        this.source = source;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.style
     *
     * @return the value of reserve_project.style
     *
     * @mbg.generated
     */
    public Integer getStyle() {
        return style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.style
     *
     * @param style the value for reserve_project.style
     *
     * @mbg.generated
     */
    public void setStyle(Integer style) {
        this.style = style;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.budget
     *
     * @return the value of reserve_project.budget
     *
     * @mbg.generated
     */
    public String getBudget() {
        return budget;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.budget
     *
     * @param budget the value for reserve_project.budget
     *
     * @mbg.generated
     */
    public void setBudget(String budget) {
        this.budget = budget == null ? null : budget.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.acreage
     *
     * @return the value of reserve_project.acreage
     *
     * @mbg.generated
     */
    public String getAcreage() {
        return acreage;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.acreage
     *
     * @param acreage the value for reserve_project.acreage
     *
     * @mbg.generated
     */
    public void setAcreage(String acreage) {
        this.acreage = acreage == null ? null : acreage.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.state
     *
     * @return the value of reserve_project.state
     *
     * @mbg.generated
     */
    public Integer getState() {
        return state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.state
     *
     * @param state the value for reserve_project.state
     *
     * @mbg.generated
     */
    public void setState(Integer state) {
        this.state = state;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.company_id
     *
     * @return the value of reserve_project.company_id
     *
     * @mbg.generated
     */
    public String getCompanyId() {
        return companyId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.company_id
     *
     * @param companyId the value for reserve_project.company_id
     *
     * @mbg.generated
     */
    public void setCompanyId(String companyId) {
        this.companyId = companyId == null ? null : companyId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.create_user_id
     *
     * @return the value of reserve_project.create_user_id
     *
     * @mbg.generated
     */
    public String getCreateUserId() {
        return createUserId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.create_user_id
     *
     * @param createUserId the value for reserve_project.create_user_id
     *
     * @mbg.generated
     */
    public void setCreateUserId(String createUserId) {
        this.createUserId = createUserId == null ? null : createUserId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.reason
     *
     * @return the value of reserve_project.reason
     *
     * @mbg.generated
     */
    public String getReason() {
        return reason;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.reason
     *
     * @param reason the value for reserve_project.reason
     *
     * @mbg.generated
     */
    public void setReason(String reason) {
        this.reason = reason == null ? null : reason.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.project_no
     *
     * @return the value of reserve_project.project_no
     *
     * @mbg.generated
     */
    public String getProjectNo() {
        return projectNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.project_no
     *
     * @param projectNo the value for reserve_project.project_no
     *
     * @mbg.generated
     */
    public void setProjectNo(String projectNo) {
        this.projectNo = projectNo == null ? null : projectNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.design_order_no
     *
     * @return the value of reserve_project.design_order_no
     *
     * @mbg.generated
     */
    public String getDesignOrderNo() {
        return designOrderNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.design_order_no
     *
     * @param designOrderNo the value for reserve_project.design_order_no
     *
     * @mbg.generated
     */
    public void setDesignOrderNo(String designOrderNo) {
        this.designOrderNo = designOrderNo == null ? null : designOrderNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.reserve_no
     *
     * @return the value of reserve_project.reserve_no
     *
     * @mbg.generated
     */
    public String getReserveNo() {
        return reserveNo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.reserve_no
     *
     * @param reserveNo the value for reserve_project.reserve_no
     *
     * @mbg.generated
     */
    public void setReserveNo(String reserveNo) {
        this.reserveNo = reserveNo == null ? null : reserveNo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.reserve_time
     *
     * @return the value of reserve_project.reserve_time
     *
     * @mbg.generated
     */
    public Date getReserveTime() {
        return reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.reserve_time
     *
     * @param reserveTime the value for reserve_project.reserve_time
     *
     * @mbg.generated
     */
    public void setReserveTime(Date reserveTime) {
        this.reserveTime = reserveTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column reserve_project.change_time
     *
     * @return the value of reserve_project.change_time
     *
     * @mbg.generated
     */
    public Date getChangeTime() {
        return changeTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column reserve_project.change_time
     *
     * @param changeTime the value for reserve_project.change_time
     *
     * @mbg.generated
     */
    public void setChangeTime(Date changeTime) {
        this.changeTime = changeTime;
    }
}