package cn.thinkfree.database.model;

import cn.thinkfree.core.model.BaseModel;
import io.swagger.annotations.ApiModelProperty;

import java.util.Date;

/**
 * Database Table Remarks:
 *   用户角色权限设置表
 *
 * This class was generated by MyBatis Generator.
 * This class corresponds to the database table user_role_set
 */
public class UserRoleSet extends BaseModel {
    /**
     * Database Column Remarks:
     *   自增id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.id
     *
     * @mbg.generated
     */
    private Short id;

    /**
     * Database Column Remarks:
     *   角色编码
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.role_code
     *
     * @mbg.generated
     */
    @ApiModelProperty("角色编码")
    private String roleCode;

    /**
     * Database Column Remarks:
     *   角色名称
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.role_name
     *
     * @mbg.generated
     */
    @ApiModelProperty("角色名称")
    private String roleName;

    /**
     * Database Column Remarks:
     *   父类id
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.pid
     *
     * @mbg.generated
     */
    private Integer pid;

    /**
     * Database Column Remarks:
     *   是否展示 1是2否（1启用2未启用3禁用）
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.is_show
     *
     * @mbg.generated
     */
    private Short isShow;

    /**
     * Database Column Remarks:
     *   更新时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.update_time
     *
     * @mbg.generated
     */
    private Date updateTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.is_enable
     *
     * @mbg.generated
     */
    private Integer isEnable;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.is_del
     *
     * @mbg.generated
     */
    private Integer isDel;

    /**
     * Database Column Remarks:
     *   创建人
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.creator
     *
     * @mbg.generated
     */
    private String creator;

    /**
     * Database Column Remarks:
     *   创建时间
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.create_time
     *
     * @mbg.generated
     */
    private Date createTime;

    /**
     * Database Column Remarks:
     *   预留字段
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column user_role_set.cf
     *
     * @mbg.generated
     */
    private String cf;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.id
     *
     * @return the value of user_role_set.id
     *
     * @mbg.generated
     */
    public Short getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.id
     *
     * @param id the value for user_role_set.id
     *
     * @mbg.generated
     */
    public void setId(Short id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.role_code
     *
     * @return the value of user_role_set.role_code
     *
     * @mbg.generated
     */
    public String getRoleCode() {
        return roleCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.role_code
     *
     * @param roleCode the value for user_role_set.role_code
     *
     * @mbg.generated
     */
    public void setRoleCode(String roleCode) {
        this.roleCode = roleCode == null ? null : roleCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.role_name
     *
     * @return the value of user_role_set.role_name
     *
     * @mbg.generated
     */
    public String getRoleName() {
        return roleName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.role_name
     *
     * @param roleName the value for user_role_set.role_name
     *
     * @mbg.generated
     */
    public void setRoleName(String roleName) {
        this.roleName = roleName == null ? null : roleName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.pid
     *
     * @return the value of user_role_set.pid
     *
     * @mbg.generated
     */
    public Integer getPid() {
        return pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.pid
     *
     * @param pid the value for user_role_set.pid
     *
     * @mbg.generated
     */
    public void setPid(Integer pid) {
        this.pid = pid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.is_show
     *
     * @return the value of user_role_set.is_show
     *
     * @mbg.generated
     */
    public Short getIsShow() {
        return isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.is_show
     *
     * @param isShow the value for user_role_set.is_show
     *
     * @mbg.generated
     */
    public void setIsShow(Short isShow) {
        this.isShow = isShow;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.update_time
     *
     * @return the value of user_role_set.update_time
     *
     * @mbg.generated
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.update_time
     *
     * @param updateTime the value for user_role_set.update_time
     *
     * @mbg.generated
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.is_enable
     *
     * @return the value of user_role_set.is_enable
     *
     * @mbg.generated
     */
    public Integer getIsEnable() {
        return isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.is_enable
     *
     * @param isEnable the value for user_role_set.is_enable
     *
     * @mbg.generated
     */
    public void setIsEnable(Integer isEnable) {
        this.isEnable = isEnable;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.is_del
     *
     * @return the value of user_role_set.is_del
     *
     * @mbg.generated
     */
    public Integer getIsDel() {
        return isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.is_del
     *
     * @param isDel the value for user_role_set.is_del
     *
     * @mbg.generated
     */
    public void setIsDel(Integer isDel) {
        this.isDel = isDel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.creator
     *
     * @return the value of user_role_set.creator
     *
     * @mbg.generated
     */
    public String getCreator() {
        return creator;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.creator
     *
     * @param creator the value for user_role_set.creator
     *
     * @mbg.generated
     */
    public void setCreator(String creator) {
        this.creator = creator == null ? null : creator.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.create_time
     *
     * @return the value of user_role_set.create_time
     *
     * @mbg.generated
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.create_time
     *
     * @param createTime the value for user_role_set.create_time
     *
     * @mbg.generated
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column user_role_set.cf
     *
     * @return the value of user_role_set.cf
     *
     * @mbg.generated
     */
    public String getCf() {
        return cf;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column user_role_set.cf
     *
     * @param cf the value for user_role_set.cf
     *
     * @mbg.generated
     */
    public void setCf(String cf) {
        this.cf = cf == null ? null : cf.trim();
    }
}