package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.AgencyContract;
import cn.thinkfree.database.model.AgencyContractExample;
import java.util.List;

import cn.thinkfree.database.vo.agency.AgencySEO;
import cn.thinkfree.database.vo.agency.MyAgencyContract;
import org.apache.ibatis.annotations.Param;

public interface AgencyContractMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract
     *
     * @mbg.generated
     */
    long countByExample(AgencyContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract
     *
     * @mbg.generated
     */
    int deleteByExample(AgencyContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract
     *
     * @mbg.generated
     */
    int insert(AgencyContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract
     *
     * @mbg.generated
     */
    int insertSelective(AgencyContract record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract
     *
     * @mbg.generated
     */
    List<AgencyContract> selectByExample(AgencyContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AgencyContract record, @Param("example") AgencyContractExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AgencyContract record, @Param("example") AgencyContractExample example);


    /**
     *分页查询 经销商合同
     */
    List<MyAgencyContract> selectPageList(AgencySEO example);

}