package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.AgencyContractHistory;
import cn.thinkfree.database.model.AgencyContractHistoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgencyContractHistoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_history
     *
     * @mbg.generated
     */
    long countByExample(AgencyContractHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_history
     *
     * @mbg.generated
     */
    int deleteByExample(AgencyContractHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_history
     *
     * @mbg.generated
     */
    int insert(AgencyContractHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_history
     *
     * @mbg.generated
     */
    int insertSelective(AgencyContractHistory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_history
     *
     * @mbg.generated
     */
    List<AgencyContractHistory> selectByExample(AgencyContractHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_history
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AgencyContractHistory record, @Param("example") AgencyContractHistoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_history
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AgencyContractHistory record, @Param("example") AgencyContractHistoryExample example);
}