package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.AgencyContractTerms;
import cn.thinkfree.database.model.AgencyContractTermsExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface AgencyContractTermsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_terms
     *
     * @mbg.generated
     */
    long countByExample(AgencyContractTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_terms
     *
     * @mbg.generated
     */
    int deleteByExample(AgencyContractTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_terms
     *
     * @mbg.generated
     */
    int insert(AgencyContractTerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_terms
     *
     * @mbg.generated
     */
    int insertSelective(AgencyContractTerms record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_terms
     *
     * @mbg.generated
     */
    List<AgencyContractTerms> selectByExample(AgencyContractTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_terms
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") AgencyContractTerms record, @Param("example") AgencyContractTermsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_agency_contract_terms
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") AgencyContractTerms record, @Param("example") AgencyContractTermsExample example);
}