package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.ApplyRefundOptionLog;
import cn.thinkfree.database.model.ApplyRefundOptionLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApplyRefundOptionLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_refund_option_log
     *
     * @mbg.generated
     */
    long countByExample(ApplyRefundOptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_refund_option_log
     *
     * @mbg.generated
     */
    int deleteByExample(ApplyRefundOptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_refund_option_log
     *
     * @mbg.generated
     */
    int insert(ApplyRefundOptionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_refund_option_log
     *
     * @mbg.generated
     */
    int insertSelective(ApplyRefundOptionLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_refund_option_log
     *
     * @mbg.generated
     */
    List<ApplyRefundOptionLog> selectByExample(ApplyRefundOptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_refund_option_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApplyRefundOptionLog record, @Param("example") ApplyRefundOptionLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table apply_refund_option_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApplyRefundOptionLog record, @Param("example") ApplyRefundOptionLogExample example);
}