package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.ApprovalFlowMessageLog;
import cn.thinkfree.database.model.ApprovalFlowMessageLogExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApprovalFlowMessageLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    long countByExample(ApprovalFlowMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    int deleteByExample(ApprovalFlowMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    int insert(ApprovalFlowMessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    int insertSelective(ApprovalFlowMessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    List<ApprovalFlowMessageLog> selectByExample(ApprovalFlowMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    ApprovalFlowMessageLog selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApprovalFlowMessageLog record, @Param("example") ApprovalFlowMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApprovalFlowMessageLog record, @Param("example") ApprovalFlowMessageLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApprovalFlowMessageLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table af_message_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApprovalFlowMessageLog record);
}