package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.ApprovalFlowPushMsg;
import cn.thinkfree.database.model.ApprovalFlowPushMsgExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ApprovalFlowPushMsgMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    long countByExample(ApprovalFlowPushMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    int deleteByExample(ApprovalFlowPushMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    int insert(ApprovalFlowPushMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    int insertSelective(ApprovalFlowPushMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    List<ApprovalFlowPushMsg> selectByExample(ApprovalFlowPushMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    ApprovalFlowPushMsg selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApprovalFlowPushMsg record, @Param("example") ApprovalFlowPushMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApprovalFlowPushMsg record, @Param("example") ApprovalFlowPushMsgExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApprovalFlowPushMsg record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_push_msg
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApprovalFlowPushMsg record);
}