package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.ApprovalFlowNodeRole;
import cn.thinkfree.database.model.ApprovalFlowNodeRoleExample;
import java.util.List;

import org.apache.ibatis.annotations.Param;

public interface ApprovalFlowNodeRoleMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    long countByExample(ApprovalFlowNodeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    int deleteByExample(ApprovalFlowNodeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    int insert(ApprovalFlowNodeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    int insertSelective(ApprovalFlowNodeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    List<ApprovalFlowNodeRole> selectByExample(ApprovalFlowNodeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    ApprovalFlowNodeRole selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ApprovalFlowNodeRole record, @Param("example") ApprovalFlowNodeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ApprovalFlowNodeRole record, @Param("example") ApprovalFlowNodeRoleExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ApprovalFlowNodeRole record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table approval_flow_roles
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ApprovalFlowNodeRole record);

    List<ApprovalFlowNodeRole> findByExternalUniqueCode(String ExternalUniqueCode);

}