package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.BranchCompany;
import cn.thinkfree.database.model.BranchCompanyExample;
import java.util.List;

import cn.thinkfree.database.vo.BranchCompanySEO;
import cn.thinkfree.database.vo.BranchCompanyVO;
import org.apache.ibatis.annotations.Param;

public interface BranchCompanyMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    long countByExample(BranchCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    int deleteByExample(BranchCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    int insert(BranchCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    int insertSelective(BranchCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    List<BranchCompany> selectByExample(BranchCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    BranchCompany selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    int updateByExampleSelective(@Param("record") BranchCompany record, @Param("example") BranchCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    int updateByExample(@Param("record") BranchCompany record, @Param("example") BranchCompanyExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    int updateByPrimaryKeySelective(BranchCompany record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_branch_company

     */
    int updateByPrimaryKey(BranchCompany record);

    BranchCompanyVO selectBranchCompanyWithPro(Integer id);

    List<BranchCompanyVO> selectBranchCompanyByParam(BranchCompanySEO branchCompanySEO);
}