package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.ConstructionOrderPay;
import cn.thinkfree.database.model.ConstructionOrderPayExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface ConstructionOrderPayMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    long countByExample(ConstructionOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    int deleteByExample(ConstructionOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    int insert(ConstructionOrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    int insertSelective(ConstructionOrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    List<ConstructionOrderPay> selectByExample(ConstructionOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    ConstructionOrderPay selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ConstructionOrderPay record, @Param("example") ConstructionOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ConstructionOrderPay record, @Param("example") ConstructionOrderPayExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ConstructionOrderPay record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table construction_order_pay
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ConstructionOrderPay record);
}