package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.PreProjectConstruction;
import cn.thinkfree.database.model.PreProjectConstructionExample;
import java.util.List;

import cn.thinkfree.database.vo.ProjectQuotationItemVO;
import cn.thinkfree.database.vo.ProjectQuotationVO;
import org.apache.ibatis.annotations.Param;

public interface PreProjectConstructionMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    long countByExample(PreProjectConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    int deleteByExample(PreProjectConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    int insert(PreProjectConstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    int insertSelective(PreProjectConstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    List<PreProjectConstruction> selectByExample(PreProjectConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    PreProjectConstruction selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    int updateByExampleSelective(@Param("record") PreProjectConstruction record, @Param("example") PreProjectConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    int updateByExample(@Param("record") PreProjectConstruction record, @Param("example") PreProjectConstructionExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    int updateByPrimaryKeySelective(PreProjectConstruction record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_construction

     */
    int updateByPrimaryKey(PreProjectConstruction record);


    /**
     * 查询项目报价单根据项目编号
     * @param projectNo
     * @return
     */
    List<ProjectQuotationItemVO> selectProjectQuotationItemVoByProjectNo(String projectNo);
}