package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.PreProjectGuide;
import cn.thinkfree.database.model.PreProjectGuideExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreProjectGuideMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    long countByExample(PreProjectGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    int deleteByExample(PreProjectGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    int insert(PreProjectGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    int insertSelective(PreProjectGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    List<PreProjectGuide> selectByExample(PreProjectGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    PreProjectGuide selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PreProjectGuide record, @Param("example") PreProjectGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PreProjectGuide record, @Param("example") PreProjectGuideExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PreProjectGuide record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_guide
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PreProjectGuide record);
}