package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.PreProjectCompanySet;
import cn.thinkfree.database.model.PreProjectCompanySetExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface PreProjectCompanySetMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    long countByExample(PreProjectCompanySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    int deleteByExample(PreProjectCompanySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    int insert(PreProjectCompanySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    int insertSelective(PreProjectCompanySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    List<PreProjectCompanySet> selectByExample(PreProjectCompanySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    PreProjectCompanySet selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") PreProjectCompanySet record, @Param("example") PreProjectCompanySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") PreProjectCompanySet record, @Param("example") PreProjectCompanySetExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(PreProjectCompanySet record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pre_project_company_set
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(PreProjectCompanySet record);
}