package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.ProjectBigSchedulingDetails;
import cn.thinkfree.database.model.ProjectBigSchedulingDetailsExample;
import java.util.List;

import cn.thinkfree.database.vo.AcceptanceResultsVO;
import cn.thinkfree.database.vo.ConstructionPlanVO;
import org.apache.ibatis.annotations.Param;

public interface ProjectBigSchedulingDetailsMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    long countByExample(ProjectBigSchedulingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    int deleteByExample(ProjectBigSchedulingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    int insert(ProjectBigSchedulingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    int insertSelective(ProjectBigSchedulingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    List<ProjectBigSchedulingDetails> selectByExample(ProjectBigSchedulingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    ProjectBigSchedulingDetails selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") ProjectBigSchedulingDetails record, @Param("example") ProjectBigSchedulingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") ProjectBigSchedulingDetails record, @Param("example") ProjectBigSchedulingDetailsExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(ProjectBigSchedulingDetails record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table project_big_scheduling_details
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(ProjectBigSchedulingDetails record);
    /**
     * 获取排期
     *
     * @param projectNo
     * @param status
     * @return
     */
    List<ProjectBigSchedulingDetails> selectByProjectNo(@Param("projectNo") String projectNo, @Param("status") Integer status);
    /**
     * @Author jiang
     * @Description 分页查询施工计划
     * @Date
     * @Param
     * @return
     **/
    List<ConstructionPlanVO> selectConstructionPlanByPage(@Param("constructionPlanVO") ConstructionPlanVO constructionPlanVO, @Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);
    /**
     * @Author jiang
     * @Description 查询施工计划总条数
     * @Date
     * @Param
     * @return
     **/
    Integer selectConstructionPlanCount(@Param("constructionPlanVO") ConstructionPlanVO constructionPlanVO);
    /**
     * @Author jiang
     * @Description 分页查询验收
     * @Date
     * @Param
     * @return
     **/
    List<AcceptanceResultsVO> selectAcceptanceResultsByPage(@Param("projectNo") String projectNo, @Param("pageNum") Integer pageNum, @Param("pageSize") Integer pageSize);
    /**
     * @Author jiang
     * @Description 查询验收总条数
     * @Date
     * @Param
     * @return
     **/
    Integer selectAcceptanceResultsCount(@Param("projectNo") String projectNo);

    /**
     * 按照项目编号将项目排期置为失效
     * @param projectNo
     * @param status
     * @return
     */
    Integer updateByProjectNo(@Param("projectNo") String projectNo,@Param("status")Integer status);

    /**
     * 根据订单编号获取验收阶段
     * @param orderNo
     * @return
     */
    List<String> selectConstructionByOrderNo(@Param("orderNo") String orderNo);

    /**
     * 根据订单编号获取验收阶段
     * @param orderNo
     * @return
     */
    List<String> selectDesignerByOrderNo(@Param("orderNo")String orderNo);
}