package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.SettlementRatioInfo;
import cn.thinkfree.database.model.SettlementRatioInfoExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SettlementRatioInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_settlement_ratio_info
     *
     * @mbg.generated
     */
    long countByExample(SettlementRatioInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_settlement_ratio_info
     *
     * @mbg.generated
     */
    int deleteByExample(SettlementRatioInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_settlement_ratio_info
     *
     * @mbg.generated
     */
    int insert(SettlementRatioInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_settlement_ratio_info
     *
     * @mbg.generated
     */
    int insertSelective(SettlementRatioInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_settlement_ratio_info
     *
     * @mbg.generated
     */
    List<SettlementRatioInfo> selectByExample(SettlementRatioInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_settlement_ratio_info
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SettlementRatioInfo record, @Param("example") SettlementRatioInfoExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_settlement_ratio_info
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SettlementRatioInfo record, @Param("example") SettlementRatioInfoExample example);
}