package cn.thinkfree.database.mapper;

import cn.thinkfree.database.model.SystemPermissionResource;
import cn.thinkfree.database.model.SystemPermissionResourceExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface SystemPermissionResourceMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    long countByExample(SystemPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    int deleteByExample(SystemPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    int insert(SystemPermissionResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    int insertSelective(SystemPermissionResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    List<SystemPermissionResource> selectByExample(SystemPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    SystemPermissionResource selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") SystemPermissionResource record, @Param("example") SystemPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") SystemPermissionResource record, @Param("example") SystemPermissionResourceExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(SystemPermissionResource record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table pc_system_permission_resource
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(SystemPermissionResource record);
}